/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Customer;

import io.swagger.annotations.*;
import io.swagger.model.NotFound;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-11-10T09:55:07.361Z")

@Api(value = "customer", description = "the customer API")
public interface CustomerApi {

    @ApiOperation(value = "Get customer information", notes = "Retrieve all customer information", response = Customer.class, authorizations = {
        @Authorization(value = "apiKey"),
        @Authorization(value = "apiSecret")
    }, tags={ "Customer", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Customer.class),
        @ApiResponse(code = 401, message = "API key is missing or invalid", response = Void.class),
    @ApiResponse(code = 404, message = "Account not found", response = NotFound.class)})
    
    @RequestMapping(value = "/customer/{query}/{searchTerm}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<Object> customerQuerySearchTermGet(@ApiParam(value = "",required=true ) @PathVariable("query") String query,@ApiParam(value = "",required=true ) @PathVariable("searchTerm") String searchTerm);

}
